language: cpp

compilers:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes 'deb http://ftp.pl.debian.org/debian/ jessie main'
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq build-essential libssl-dev pkg-config libprotobuf-dev protobuf-compiler
  - sudo apt-get install -qq qt5-qmake qt5-default qtbase5-dev qttools5-dev-tools qtdeclarative5-dev qtmultimedia5-dev
  - sudo apt-get install -qq tor

script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make