language: cpp

compilers:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes 'deb http://ftp.pl.debian.org/debian/ jessie main'
  - sudo apt-get update -qq

before_install:
  - wget http://ftp.us.debian.org/debian/pool/main/q/qtbase-opensource-src/qt5-default_5.3.2+dfsg-4+deb8u1_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/q/qttools-opensource-src/qttools5-dev-tools_5.3.2-3_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/q/qtdeclarative-opensource-src/qtdeclarative5-dev_5.3.2-4_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/q/qtmultimedia-opensource-src/qtmultimedia5-dev_5.3.2-5_amd64.deb

install:
  - sudo apt-get install -qq build-essential libssl-dev pkg-config libprotobuf-dev protobuf-compiler
  - sudo dpkg -i qt5-default_5.3.2+dfsg-4+deb8u1_amd64.deb qttools5-dev-tools_5.3.2-3_amd64.deb qtdeclarative5-dev_5.3.2-4_amd64.deb qtmultimedia5-dev_5.3.2-5_amd64.deb || true
  - sudo apt-get -f install
  - sudo apt-get install -qq tor

script:
  - qtchooser -list-versions
  - qmake -qt=qt5
  - make